### ISSUE TITLE
Speed of \JsonMachine\JsonMachine::fromFile

### ISSUE THREAD

**Issue by TechOverflow** [halaxa/json-machine#1] opened 2018-12-05 04:35 UTC
Hi!

Is it normal for a response to take 8-9 seconds on a 32MB file? When using json_decode, it was maybe a second or two (at the cost of resources).

I am simply using 
`$array = \JsonMachine\JsonMachine::fromFile($file);`
and matching an email with foreach to return all objects containing that email (usually 5-10 objects and 20kB or so).

Cheers

**Comment by halaxa** [comment] 2018-12-05 12:12
Hello. Yes, it seems normal for most PCs.

If `json_decode` works for you better, use that. When it starts failing because of memory, use JsonMachine.

The main advantage of this package is **constant memory consumption** and quite constant speed. Of course the speed can't mostly measure with native implementation, but that's not the goal. The goal is to be memory efficient on JSON streams of any length. In terms of speed, `json_decode` fluctuates greatly on huge files.

By the way, 5x slower than native (in your case) is not that bad. With JSON files with size of 100 MB and up it is sometimes even faster than `json_decode`. And while on 100 MB file `json_decode` eats about 1 GB of memory, JsonMachine is constantly at about 800 kB.

**Comment by TechOverflow** [comment] 2018-12-05 20:00
The delay is actually caused by the foreach, which is due to the 27 thousand objects. I'll try to cut down on the amount of data in each object to make it more efficient.

**Comment by halaxa** [comment] 2018-12-05 20:53
Take a look at `test/performance/testPerformace.php`. You may get some hints. If you provided part or pseudo-part of your json file, we could discuss it here.

**Comment by halaxa** [comment] 2018-12-17 20:40
Closing as not a bug for now.

**Closed by halaxa** 2018-12-17 20:40 UTC

**Comment by halaxa** [comment] 2023-05-06 20:38
This might be of help #97
